<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>

		<RootNamespace>DVLD</RootNamespace>
		<AssemblyName>DVLD</AssemblyName>

		<Platforms>AnyCPU</Platforms>
		<PlatformTarget>AnyCPU</PlatformTarget>

		<ApplicationIcon />
		<StartupObject>DVLD.Program</StartupObject>

		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
	</PropertyGroup>

	<ItemGroup>

		<!-- Project Reference -->
		<ProjectReference Include="..\DVLD_Business\DVLD_Business.csproj" />

	</ItemGroup>

	<ItemGroup>

		<!-- Resources -->
		<None Update="Resources\application.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\group.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\driver.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\management.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\account-management.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\Logo Final.jpg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\Q0rL2.jpg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\drivers-license.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\portfolio.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\stamp.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\website.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\resume.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\project.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\reset-password.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\logout.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\guarantee.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\renewal.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\testing.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\press.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\test.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\place.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\worldwide-shipping.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\stamp %281%29.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\project-management.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\compliance.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\notes.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\user.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\businessman.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="Resources\woman.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

	</ItemGroup>

</Project>